//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCuoiKhoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonDatHangs = new HashSet<ChiTietDonDatHang>();
        }
    
        public int ID_SanPham { get; set; }
        public string TenSanPham { get; set; }
        public string Avatar { get; set; }
        public string HinhAnhMoTa { get; set; }
        public string GioiThieu { get; set; }
        public string ThongTinChiTiet { get; set; }
        public string TenThuongHieu { get; set; }
        public Nullable<bool> SanPhamKhuyenMai { get; set; }
        public Nullable<bool> SanPhamBanChay { get; set; }
        public Nullable<decimal> GiaGoc { get; set; }
        public Nullable<decimal> GiaKhuyenMai { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<int> ID_DanhMucCon { get; set; }
        public Nullable<int> ID_DanhMuc { get; set; }
        public Nullable<int> ID_ThuongHieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonDatHang> ChiTietDonDatHangs { get; set; }
        public virtual DanhMucCon DanhMucCon { get; set; }
        public virtual DanhMucSP DanhMucSP { get; set; }
        public virtual ThuongHieu ThuongHieu { get; set; }
    }
}
